### PR TITLE
Sensor applet

### PR DESCRIPTION
**Pull request by QORTEC**
**ikeydoherty**
> this should have been at most 2 commits, one to introduce the applet, and a second to then tie it into the main build system

**ikeydoherty**
> I keep seeing merge commits here that I simply cannot merge into the repo

Ikey usually does not accept pull requests when there are [to many] "unnecessary" commits.
You will probably need to clean up your commit history before your applet will be pulled upstream.

I would like to see this applet added to budgie, so if you need any help with cleaning up your commit history let me know.

---

My fork and yours should be identical but with the one difference that the commit history is cleaned up

### CODE REVIEW

**Comment by QORTEC** [comment]
the git history does not get wiped when accepting this pull request, you will need to use the terminal

**Comment by QORTEC** [comment]
@memoryleakx 
I was just looking at the commit messages it looks like you are probably using the GitHub Web UI...

Here are the instructions to update your Git repository and cleanup your commit history (using the terminal):
https://gist.githubusercontent.com/QORTEC/9efaec0da00fabfc280a7b36926f3f38/raw/fe5f2489c57d47791cd08a6e51fc46713fa4f5d8/sensor-applet.bash

You will need you the **git** terminal application.

**Comment by memoryleakx** [comment]
Thank you for your Help ;)

**Comment by QORTEC** [comment]
I'm happy I could help; 
I'm also "relatively new" to GitHub and contributing to Solus-Project.
Not that long ago I had a pull request that looked quite similar to yours...

**Pull request merged**
